# Generated by Django 2.2.7 on 2019-11-19 21:40

import catalog.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=catalog.util.get_image_path),
        ),
    ]
